"""
Automatic re-engagement — two rules, DeepSeek writes the actual words.

RULE 1 (rescue nudge): Emma spoke last, the fan went silent for
NUDGE_AFTER_MINUTES, and the conversation did NOT end with a goodbye →
Emma plays the victim a little ("I feel like I don't matter to you...").
Once per silence episode.

RULE 2 (good morning): the fan has been silent for many hours →
next morning Emma opens with warmth ("good morning... I was thinking
about you last night"). Once per day, only during morning hours.

Only the TRIGGER is rule-based. The message itself is generated by
DeepSeek with the full conversation, memory, lessons and language mirror.
"""
from __future__ import annotations

import os
import random
import re
import time
from datetime import datetime, timedelta, timezone
from typing import List, Optional

from core import convo_log, fan_memory, language, persona_time
from core.reply_engine import (
    fanvue_messages_to_turns,
    generate_emma_reply,
    split_into_messages,
)
from core.turn_policy import TurnDecision

NUDGE_AFTER_MINUTES = int(os.getenv("NUDGE_AFTER_MINUTES", "5"))
GOODMORNING_AFTER_HOURS = int(os.getenv("GOODMORNING_AFTER_HOURS", "14"))
GOODMORNING_HOUR_START = int(os.getenv("GOODMORNING_HOUR_START", "8"))
GOODMORNING_HOUR_END = int(os.getenv("GOODMORNING_HOUR_END", "13"))

# If the convo ended with a goodbye, silence is normal — don't guilt-trip.
_FAREWELL = re.compile(
    r"(?i)\b("
    r"good ?night|gn|bye|see (you|ya)|talk (later|soon|tomorrow)|ttyl|gtg|"
    r"going to (bed|sleep)|sleep well|sweet dreams|"
    r"adi[oó]s|buenas noches|hasta (ma[nñ]ana|luego|pronto)|me voy|"
    r"nos vemos|descansa|dulces sue[nñ]os|a dormir"
    r")\b"
)

NUDGE_TRIGGER = (
    "[SYSTEM: He went quiet {minutes} minutes ago, right after your last message — "
    "the conversation was left hanging mid-flow. Send a short, natural follow-up "
    "playing the victim a LITTLE: you feel ignored, like you don't matter to him, "
    "like he forgot about you. Needy but cute, never angry, never desperate walls "
    "of text. 1-2 short lines max. Do NOT sell anything. Do NOT mention this note.]"
)

GOODMORNING_TRIGGER = (
    "[SYSTEM: He never answered and it's now the next morning in Los Angeles "
    "({hours}h of silence). Open fresh and warm: good morning, you thought about him "
    "last night, you woke up missing him — something in that spirit, natural and "
    "personal to YOUR conversation. 1-2 short lines. Light, no guilt-tripping, "
    "no selling. Do NOT mention this note.]"
)


def _msg_ts(msg: dict) -> Optional[datetime]:
    for key in ("createdAt", "created_at", "sentAt", "sent_at", "timestamp"):
        v = msg.get(key)
        if not v:
            continue
        try:
            return datetime.fromisoformat(str(v).replace("Z", "+00:00"))
        except ValueError:
            continue
    return None


def _sender_uuid(msg: dict) -> Optional[str]:
    sender = msg.get("sender")
    if isinstance(sender, dict):
        return sender.get("uuid")
    if isinstance(sender, str):
        return sender
    return None


def _last_fan_text(messages: List[dict], fan_uuid: str) -> str:
    for msg in messages:  # newest-first
        if _sender_uuid(msg) == fan_uuid and (msg.get("text") or "").strip():
            return msg["text"].strip()
    return ""


def _ended_with_farewell(messages: List[dict]) -> bool:
    texts = [(m.get("text") or "") for m in messages[:2]]
    return any(_FAREWELL.search(t) for t in texts if t)


def _send_generated(
    fv,
    fan_uuid: str,
    fan_handle: str,
    messages: List[dict],
    creator_uuid: str,
    trigger: str,
    kind: str,
) -> bool:
    turns = fanvue_messages_to_turns(messages, fan_uuid, creator_uuid, max_messages=14)
    mem = fan_memory.get(fan_uuid)
    last_fan = _last_fan_text(messages, fan_uuid)
    want_spanish = language.fan_wants_spanish(last_fan, mem) if last_fan else bool(
        mem.get("prefer_spanish")
    )

    decision = TurnDecision(
        mode="chill",
        reason=f"re-engagement:{kind}",
        max_bubbles=2,
        allow_ppv_talk=False,
        allow_price=False,
    )
    try:
        reply, _ = generate_emma_reply(
            trigger,
            history_turns=turns,
            fan_handle=fan_handle,
            fan_uuid=fan_uuid,
            decision=decision,
            want_spanish=want_spanish,
            pack_id="phase_reengage",
        )
    except Exception as e:
        print(f"   ⚠️ {kind} generation failed for @{fan_handle}: {e}")
        return False
    if not reply.strip():
        return False

    bubbles = split_into_messages(reply, max_bubbles=2)
    for i, bubble in enumerate(bubbles):
        try:
            fv.send_typing_indicator(fan_uuid, True)
        except Exception:
            pass
        time.sleep(random.uniform(3.0, 7.0) if i == 0 else random.uniform(2.5, 5.0))
        fv.send_message(fan_uuid, bubble)
        try:
            fv.send_typing_indicator(fan_uuid, False)
        except Exception:
            pass

    fan_memory.mark_nudge(fan_uuid, kind, fan_handle=fan_handle)
    try:
        convo_log.log_turn(
            fan_uuid,
            fan_handle=fan_handle,
            fan_message=f"[silence — {kind} trigger]",
            reply=reply,
            bubbles=len(bubbles),
            mode=kind,
            mode_reason=f"auto re-engagement {kind}",
        )
    except Exception:
        pass
    print(f"   💌 {kind} sent to @{fan_handle}: {reply[:70]}")
    return True


def run_pass(fv, chats: List[dict], creator_uuid: str) -> int:
    """Check silent chats; send at most a few re-engagements per pass."""
    sent = 0
    now = datetime.now(timezone.utc)
    # Emma lives in LA — the "morning" window follows HER clock, not the server's
    local_hour = persona_time.la_now().hour

    for chat in chats:
        if sent >= 3:  # keep passes cheap and non-spammy
            break
        user = chat.get("user", {})
        fan_uuid = user.get("uuid")
        fan_handle = user.get("handle", "fan")
        if not fan_uuid:
            continue

        mem = fan_memory.get(fan_uuid)
        # Only fans who have actually talked to us before
        if not mem or int(mem.get("messages") or 0) < 1:
            continue

        try:
            messages = fv.get_messages(fan_uuid, size=8)
        except Exception:
            continue
        if not messages:
            continue

        newest = messages[0]
        if _sender_uuid(newest) != creator_uuid:
            continue  # fan spoke last — normal reply flow handles it
        ts = _msg_ts(newest)
        if not ts:
            continue
        silence = now - ts

        if _ended_with_farewell(messages):
            # said goodbye → only the next-day good morning applies
            pass_farewell = True
        else:
            pass_farewell = False

        # RULE 2 — next-day good morning (once per LA day, LA morning hours)
        today = persona_time.la_today()
        if (
            silence >= timedelta(hours=GOODMORNING_AFTER_HOURS)
            and mem.get("last_goodmorning_day") != today
            and GOODMORNING_HOUR_START <= local_hour < GOODMORNING_HOUR_END
        ):
            trigger = GOODMORNING_TRIGGER.format(hours=int(silence.total_seconds() // 3600))
            if _send_generated(
                fv, fan_uuid, fan_handle, messages, creator_uuid, trigger, "goodmorning"
            ):
                sent += 1
            continue

        # RULE 1 — 5-minute rescue nudge (once per silence episode)
        if (
            not pass_farewell
            and not mem.get("nudge_sent_episode")
            and timedelta(minutes=NUDGE_AFTER_MINUTES)
            <= silence
            < timedelta(hours=GOODMORNING_AFTER_HOURS)
        ):
            trigger = NUDGE_TRIGGER.format(minutes=int(silence.total_seconds() // 60))
            if _send_generated(
                fv, fan_uuid, fan_handle, messages, creator_uuid, trigger, "nudge"
            ):
                sent += 1

    return sent
